#!/bin/sh
#
# ts-magicDNS-daemon.sh
#
# Installs a systemd service + timer that keeps /etc/hosts
# updated with Tailscale peers, using your domain "uygar.live".
#

set -euo pipefail

DOMAIN="uygar.live"
SCRIPT_PATH="/usr/local/bin/update-tailscale-hosts.sh"
SERVICE_PATH="/etc/systemd/system/update-tailscale-hosts.service"
TIMER_PATH="/etc/systemd/system/update-tailscale-hosts.timer"

echo "[*] Installing Tailscale hosts updater..."

# Ensure dependencies
if ! command -v jq >/dev/null 2>&1; then
  echo "[*] Installing jq..."
  apk add --no-cache jq
fi

# Install the updater script
cat > "$SCRIPT_PATH" <<'EOF'
#!/bin/sh
set -euo pipefail

DOMAIN="uygar.live"
HOSTS_FILE="/etc/hosts"
TMP_FILE="$(mktemp)"

tailscale status --json | jq -r \
  --arg domain "$DOMAIN" '
  .Peer | to_entries[] |
  select(.value.HostName != null and .value.HostName != "" and .value.HostName != "localhost") |
  (.value.TailscaleIPs[0] + " " +
   .value.HostName + "." + $domain + " " +
   .value.HostName)
' > "$TMP_FILE"

# Remove old Tailscale block but keep everything else
awk '
  /^# TAILSCALE BEGIN/ {inblock=1; next}
  /^# TAILSCALE END/   {inblock=0; next}
  inblock==0 {print}
' "$HOSTS_FILE" > "$HOSTS_FILE.tmp"

# Append new block
{
  echo "# TAILSCALE BEGIN (auto-generated by update-tailscale-hosts.sh)"
  cat "$TMP_FILE"
  echo "# TAILSCALE END"
} >> "$HOSTS_FILE.tmp"

# Replace atomically
mv "$HOSTS_FILE.tmp" "$HOSTS_FILE"
rm -f "$TMP_FILE"

echo "[OK] /etc/hosts updated with Tailscale entries."
EOF

chmod +x "$SCRIPT_PATH"

# Create systemd service
cat > "$SERVICE_PATH" <<EOF
[Unit]
Description=Update /etc/hosts from Tailscale

[Service]
Type=oneshot
ExecStart=$SCRIPT_PATH
EOF

# Create systemd timer
cat > "$TIMER_PATH" <<EOF
[Unit]
Description=Run Tailscale hosts updater every 5 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=5min
Unit=update-tailscale-hosts.service

[Install]
WantedBy=timers.target
EOF

# Enable and start
systemctl daemon-reload
systemctl enable --now update-tailscale-hosts.timer

# Run once immediately
"$SCRIPT_PATH"

echo "[✓] Tailscale MagicDNS daemon installed successfully."
echo "    Check /etc/hosts for entries like 'host.${DOMAIN}'"
