#!/bin/bash
#
# ts-magicDNS-daemon.sh
#
# Installs a systemd service + timer that keeps /etc/hosts
# updated with Tailscale peers, using your domain "uygar.live".
#

set -euo pipefail

DOMAIN="uygar.live"
SCRIPT_PATH="/usr/local/bin/update-tailscale-hosts.sh"
SERVICE_PATH="/etc/systemd/system/update-tailscale-hosts.service"
TIMER_PATH="/etc/systemd/system/update-tailscale-hosts.timer"

echo "[*] Installing Tailscale hosts updater..."

# Ensure dependencies
if ! command -v jq >/dev/null; then
  echo "[*] Installing jq..."
  if command -v apt-get >/dev/null; then
    sudo apt-get update && sudo apt-get install -y jq
  elif command -v dnf >/dev/null; then
    sudo dnf install -y jq
  elif command -v yum >/dev/null; then
    sudo yum install -y jq
  else
    echo "[!] Could not install jq automatically. Please install it manually."
    exit 1
  fi
fi

# Install the updater script
sudo tee "$SCRIPT_PATH" > /dev/null <<"EOF"

## ========= update-tailscale-hosts.sh ===================== ##
#!/bin/bash
set -euo pipefail

DOMAIN="uygar.live"
HOSTS_FILE="/etc/hosts"
TMP_FILE="$(mktemp)"

# Extract peers, skip null/empty/localhost hostnames
tailscale status --json | jq -r \
  --arg domain "$DOMAIN" '
  .Peer | to_entries[] |
  select(.value.HostName != null and .value.HostName != "" and .value.HostName != "localhost") |
  ($peer := .) |
  ($peer.value.TailscaleIPs[0] + " " +
   $peer.value.HostName + "." + $domain + " " +
   $peer.value.HostName)
' > "$TMP_FILE"

# Clean out ALL old blocks
awk '
  /^# TAILSCALE BEGIN/ {skip=1; next}
  /^# TAILSCALE END/ {skip=0; next}
  skip==0 {print}
' "$HOSTS_FILE" > "$HOSTS_FILE.tmp"

# Append new block
{
  echo "# TAILSCALE BEGIN (auto-generated by update-tailscale-hosts.sh)"
  cat "$TMP_FILE"
  echo "# TAILSCALE END"
} >> "$HOSTS_FILE.tmp"

# Replace atomically
mv "$HOSTS_FILE.tmp" "$HOSTS_FILE"
rm -f "$TMP_FILE"

echo "[OK] /etc/hosts updated with Tailscale entries."

## ========= update-tailscale-hosts.sh ===================== ##
EOF

sudo chmod +x "$SCRIPT_PATH"

# Create systemd service
sudo tee "$SERVICE_PATH" > /dev/null <<EOF
[Unit]
Description=Update /etc/hosts from Tailscale

[Service]
Type=oneshot
ExecStart=$SCRIPT_PATH
EOF

# Create systemd timer
sudo tee "$TIMER_PATH" > /dev/null <<EOF
[Unit]
Description=Run Tailscale hosts updater every 5 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=5min
Unit=update-tailscale-hosts.service

[Install]
WantedBy=timers.target
EOF

# Enable and start
sudo systemctl daemon-reload
sudo systemctl enable --now update-tailscale-hosts.timer

# Run once immediately
sudo "$SCRIPT_PATH"

echo "[✓] Tailscale MagicDNS daemon installed successfully."
echo "    Check /etc/hosts for entries like 'host.uygar.live'"
