# update-tailscale-hosts.ps1
# PowerShell port of MagicDNS updater
# Updates Windows hosts file with Tailscale peers

$Domain    = "uygar.live"
$HostsFile = "$env:SystemRoot\System32\drivers\etc\hosts"
$TmpFile   = New-TemporaryFile

# Get Tailscale status JSON
$tsStatus = & tailscale status --json | ConvertFrom-Json

# Extract peers (skip null/empty/localhost hostnames)
$lines = foreach ($peer in $tsStatus.Peer.PSObject.Properties) {
    $val = $peer.Value
    if ($val.HostName -and $val.HostName -ne "localhost" -and $val.TailscaleIPs) {
        $ip = $val.TailscaleIPs[0]
        "$ip $($val.HostName).$Domain $($val.HostName)"
    }
}

# Read existing hosts and remove all old Tailscale blocks
$existing = @()
$skip = $false
foreach ($line in Get-Content $HostsFile) {
    if ($line -match '^# TAILSCALE BEGIN') { $skip = $true; continue }
    if ($line -match '^# TAILSCALE END')   { $skip = $false; continue }
    if (-not $skip) { $existing += $line }
}

# Write back cleaned hosts file
$existing | Set-Content $TmpFile

# Append new block
Add-Content $TmpFile "# TAILSCALE BEGIN (auto-generated by update-tailscale-hosts.ps1)"
$lines | Sort-Object -Unique | Add-Content $TmpFile
Add-Content $TmpFile "# TAILSCALE END"

# Replace atomically
Copy-Item $TmpFile $HostsFile -Force
Remove-Item $TmpFile

Write-Host "[OK] Hosts file updated with Tailscale entries."
